version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: restaurants

    # image: nginx
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: restaurants
