version: "3.9"

services:
  db:
    container_name: postgres
    restart: always
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - flask-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  app:
    container_name: app
    restart: always
    build:
      context: .
      network: host
    ports:
      - "80:5000"
    depends_on:
      - postgres

volumes:
  flask-db:
    name: flask-db